baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Coding cheats"
theme = "hugo-notepadium"
copyright = "©2020 mycodingcheats."
enableInlineShortcodes= true
enableEmoji=true

[params]
style = "auto"  # default: "auto", based on system. "light": light theme, "dark": dark theme.
logo = "images/logo.png"
slogan = "my coding cheats"

[params.assets]
css = ["css/custom.css"]  

[markup.highlight]
codeFences = true
noClasses = false

#[markup.goldmark.renderer]
#unsafe = true  # enable raw HTML in Markdown

[params.comments]
enable = false

[params.nav]
showTags = true  

# disqus
#disqusShortname = "Parmod Kumar"