baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Coding cheats"
theme = "hugo-notepadium"
copyright = "©2020 mycodingcheats."
enableInlineShortcodes= true
enableEmoji=true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
style = "auto"  # default: "auto", based on system. "light": light theme, "dark": dark theme.
logo = "images/logo.png"
slogan = "my coding cheats"


[markup.highlight]
codeFences = true
noClasses = false

[params.comments]
enable = false