name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'

      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_REPO_OAUTH_TOKEN }}
          external_repository: parmod-arora/parmod-arora.github.io
          publish_dir: ./public
          keep_files: true
          user_name: parmod-arora
          user_email: parmodkrarora@gmail.com
          publish_branch: master
